[package]
name = "revme-host"
version.workspace = true
edition.workspace = true
default-run = "revme-host"
publish = false

[dependencies]
zkm-sdk = { workspace = true }
guest-std = { git = "https://github.com/zkMIPS/revme.git", package = "guest-std", branch = "cbor-zkm" }
models = { git = "https://github.com/zkMIPS/revme", package = "models", branch = "cbor-zkm" }
bincode = "1.3.3"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[build-dependencies]
zkm-build = { workspace = true }

[[bin]]
name = "revme-host"
path = "src/main.rs"
